programigos/programigos/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from preguntar import views
from preguntar.views import primer, detalle

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^preguntas/$',views.primer, name="primer"),
	url(r'^preguntas/(?P<pregunta_id>\d+)/$', views.detalle, name="detalle"),
]

programigos/preguntar/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone

# Create your models here.
class Pregunta(models.Model):
	asunto = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.asunto

	def publicadoHoy(self):
		return self.fecha.date() == timezone.now().date()
	publicadoHoy.boolean = True
	publicadoHoy.descripcionCorta = 'Preguntado hoy?'


class Respuesta(models.Model):
	Pregunta = models.ForeignKey(Pregunta)
	contenido = models.TextField()
	mejor = models.BooleanField("The Best is ",default=False)

	def __str__(self):
		return self.contenido

programigos/preguntar/views.py
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals
#from django.shortcuts import render
from django.http import HttpResponse,Http404
from preguntar.models import Pregunta
from django.shortcuts import get_object_or_404, render_to_response

# Create your views here.

def primer(request):
	pregunta = Pregunta.objects.all()
	return render_to_response("preguntar/primer.html",{"pregunta": pregunta})

def detalle(request, pregunta_id):
	pregunta = get_object_or_404(Pregunta,pk=pregunta_id)
	return render_to_response("preguntar/detalle.html",{"pregunta": pregunta})

#[template_directory]/preguntar/primer.html

programigos/templates/preguntar/detalle.html
<html>
	<head>
		<title>Respuesta</title>
	</head>
	<body>
		<h2>{{pregunta.asunto}}?</h2>
		<p><b>Publicado:</b> {{pregunta.fecha|date:"D, d/m/Y"}}</p>
		<p>
		{% if pregunta.descripcion %}
			{{pregunta.descripcion}}
		{% else %}
			No se ha incluido descripción
		{% endif %}
		</p>
	<h3>Respuestas</h3>
	<ul>
		{% for respuesta in pregunta.respuesta_set.all %}
			<li>{{respuesta.contenido|safe}}</li>
		{% empty %}
			<li>Aún no hay respuestas</li>
		{% endfor %}
	</ul>
	</body>
	</html>

programigos/templates/preguntar/primer.html
<html>
	<head>
		<title>Preguntas</title>
	</head>
	<body>
		{% for Pregunta in pregunta %}
			<a href="{% url 'detalle' Pregunta.id %}">{{ Pregunta.asunto}} ?</a><br/>
{% endfor %}
	</body>
</html>